name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          CHROME_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114)
          sudo apt-get install -y \
            google-chrome-stable=$CHROME_VERSION-1 \
            libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 \
            libxi6 libxtst6 libxrandr2 libasound2 \
            libpangocairo-1.0-0 libgtk-3-0 xvfb

      - name: Set up ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME/chromedriver
          rm chromedriver_linux64.zip
          echo "$HOME/chromedriver" >> $GITHUB_PATH

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
        env:
          DISPLAY: ":99.0"

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Build and Test with Maven
        run: mvn -B test --file pom.xml
        env:
          DISPLAY: ":99.0"





    
